use crate::backend::CommandRunner;
use crate::error::{AppError, AppResult};
use serde_json::Value;
use std::path::{Path, PathBuf};

/// Entry-point installer script bundled under `resources/faststart/`.
pub const FASTSTART_ENTRY_SCRIPT: &str = "btx-agent-setup.py";

#[derive(Debug, Clone, PartialEq)]
pub struct FaststartResult {
    pub btxd: PathBuf,
    pub btx_cli: PathBuf,
    pub faststart_conf: PathBuf,
    pub mining_results_dir: Option<PathBuf>,
}

/// Reconstruct the install paths a *returning* user already has on disk,
/// WITHOUT re-running the (network-bound, multi-second) faststart installer.
///
/// `btx-agent-setup.py` installs binaries to a deterministic location:
/// `~/.local/btx/<release_tag>/<platform_id>/` (recursively containing `btxd`
/// and `btx-cli`), and `btx-faststart.py` writes the node config to
/// `<datadir>/faststart/faststart.conf`. We mirror that convention here so the
/// returning-user path can start the node directly. Returns `None` if the
/// expected binaries can't be found (e.g. a partially-removed install), so the
/// caller can fall back to a full re-install.
pub fn returning_launch_paths(datadir: &Path, release_tag: &str) -> Option<FaststartResult> {
    let home = crate::platform::home_dir()?;
    let install_dir = home
        .join(".local")
        .join("btx")
        .join(release_tag)
        .join(platform_id());

    let btxd = find_binary(&install_dir, &crate::platform::exe_name("btxd"))?;
    let btx_cli = find_binary(&install_dir, &crate::platform::exe_name("btx-cli"))?;
    let faststart_conf = datadir.join("faststart").join("faststart.conf");
    let mining_results_dir = {
        let d = datadir.join("mining-ops");
        d.exists().then_some(d)
    };

    Some(FaststartResult {
        btxd,
        btx_cli,
        faststart_conf,
        mining_results_dir,
    })
}

/// Mining binaries provisioned from the bundle. We deliberately SKIP the Qt GUI
/// (`btx-qt`, ~37 MB) and the test harness (`test_btx`, ~44 MB) — EasyBTX has its
/// own UI and never runs them — so the bundle stays ~20 MB. `btxd` + `btx-cli`
/// are mandatory; the matmul tools are best-effort (mining still works via btxd's
/// linked Metal backend if a tool is absent).
pub const BUNDLED_NODE_BINARIES: &[&str] = &[
    "btxd",
    "btx-cli",
    "btx-matmul-backend-info",
    "btx-matmul-solve-bench",
    "btx-matmul-metal-bench",
];

/// The `miner` preset faststart.conf (minus the `addnode=` lines, which
/// `ensure_addnodes_in_conf` appends right after provisioning).
///
/// `prune=0` (NOT the legacy python preset's `prune=4096`) is DELIBERATE and the
/// fix for the "restart → full re-sync" bug: on a PRUNED node, an unclean btxd
/// shutdown (OS restart, lid close, force-quit, power loss) leaves the shielded-
/// state DB needing a rebuild that reads HISTORICAL blocks — which pruning deleted
/// (`ReadRawBlock: OpenBlockFile failed nFile=-1`) → "Failed to initialize shielded
/// state database" → btxd won't start → the app's repair wipes the chain → hours of
/// re-sync. Keeping every block (prune=0) means the shielded rebuild always has its
/// blocks, so a restart just RESUMES. assumeutxo still fast-starts (snapshot → mine
/// at the base height) while the full chain backfills in the background; it just
/// KEEPS the blocks instead of deleting them. Costs more disk, buys restart-safety.
pub const MINER_FASTSTART_CONF: &str = "\
# Generated by EasyBTX (self-contained native faststart)
# Preset: miner
server=1
listen=1
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
# prune=0 keeps ALL blocks so btxd can rebuild shielded state after an unclean
# shutdown. A pruned node CANNOT (it deleted the blocks the rebuild needs), which
# turns every hard restart into a multi-hour re-sync. Do not re-enable pruning.
# blockfilterindex/coinstatsindex are intentionally OFF: EasyBTX never queries
# them (no gettxoutsetinfo/getblockfilter caller), and on an un-pruned node they
# add GBs of dead index. disk::reclaim_disk strips them from older installs too.
prune=0
retainshieldedcommitmentindex=1
miningminoutboundpeers=2
miningminsyncedoutboundpeers=1
miningmaxheaderlag=8
";

/// The `node` preset faststart.conf for the standalone easyBTX Node app: the
/// miner preset minus the three `mining*` chain-guard tuning keys (the node app
/// never mines, so btxd's defaults are right). Everything else is identical —
/// especially `prune=0`, which keeps restarts safe (see the miner-conf comment
/// above), and localhost-only RPC.
pub const NODE_FASTSTART_CONF: &str = "\
# Generated by easyBTX Node (self-contained native faststart)
# Preset: node
server=1
listen=1
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
# prune=0 keeps ALL blocks so btxd can rebuild shielded state after an unclean
# shutdown. A pruned node CANNOT (it deleted the blocks the rebuild needs), which
# turns every hard restart into a multi-hour re-sync. Do not re-enable pruning.
prune=0
retainshieldedcommitmentindex=1
# Deep-reorg protection. btxd ships this DISABLED in every built-in profile, so
# without these lines a node follows whichever branch carries the most chainwork.
# During the 2026-08-11 split that was the WRONG one: a competing branch forked
# at 185544 and ran longer in headers (186234 against the canonical 186011), so
# following chainwork alone meant a ~464-block reorg onto a chain whose blocks
# the rest of the network does not count.
#
# Parking at depth 6 makes the node refuse to auto-switch that far and hold its
# tip instead. That is the safe direction: a node that stops is recoverable and
# visible, a node that silently reorganises onto a dead branch looks perfectly
# healthy while being useless. Depths follow the BTX team's own guidance issued
# during the incident.
#
# ⚠ This protects a node going FORWARD. It does NOT rescue one already sunk on a
# stale branch — chainwork keeps those locked, and recovery needs
# `invalidateblock` plus blocks from a known-good peer.
parkdeepreorg=1
maxreorgdepthpark=6
maxreorgdepthwarn=3
";

/// The KEEPER preset: a small pruned node whose job is serving signed
/// confirmations (attestations) — the visual, one-click version of keeper/.
///
/// ⚠ ENGINE-GATED. This conf is only safe on a bundled btxd that contains
/// BOTH upstream fixes:
///   - `1d73e70b` — rebuild_from_chain refuses the genesis wipe when
///     ahead-of-snapshot blocks are missing (without it, pruned + snapshot +
///     one unclean shutdown = the bricked-datadir scar `prune=0` exists for);
///   - `0ece8ef4` — trusted mirrors may serve GETMMATTEST (without it a
///     keeper ADVERTISES the archive bit and answers nothing — the exact
///     network-wide bug the 2026-08-17 census decomposed).
/// The pin has MOVED since this warning was written. It is `v0.34.5`, which the
/// denylist in `engine_supports_keeper_profile` does not name, so this conf
/// ships to keepers today — the opposite of what this comment used to say in
/// the present tense ("the pinned 1e51f0d1 predates both"). Note carefully what
/// that admission is and is not: it is a denylist DEFAULT, not a positive
/// verification that v0.34.5 contains `1d73e70b` and `0ece8ef4`. Nothing in
/// this repository checks that. Callers select this conf through
/// `conf_for_profile`, which applies the gate; never pass it directly.
pub const NODE_KEEPER_CONF: &str = "\
# Generated by easyBTX Node (self-contained native faststart)
# Preset: keeper — pruned, serves signed confirmations
server=1
listen=1
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
# Keeper keeps ~10 GB of recent blocks, not the whole chain. Safe ONLY on an
# engine with the pruned-snapshot rebuild fix (see the gate in installer.rs).
prune=10000
retainshieldedcommitmentindex=1
# Serve signed confirmations — the point of the profile.
matmulattestationserve=1
# Deep-reorg protection: same posture as the full-node preset (2026-08-11 split).
parkdeepreorg=1
maxreorgdepthpark=6
maxreorgdepthwarn=3
";

/// Does the bundled node engine support the keeper profile? Keyed on the
/// node release TAG the app pins (`commands.rs::NODE_RELEASE_TAG`), because
/// the tag is the one identity the app controls end to end.
///
/// TODAY IT ANSWERS YES. The pin is `v0.34.5`, which is not in the denylist
/// below, so keepers get the pruned conf. This doc previously said the shipped
/// engine answers NO, which was true of `v0.33.3-pr105b` and stopped being true
/// when the pin moved — and nothing failed, because nothing asserted it. See
/// `the_shipped_pin_makes_a_deliberate_keeper_decision` in the node app, which
/// forces the next pin bump to make this choice consciously rather than
/// inherit whatever the denylist happens to default to.
///
/// READ THE BODY BEFORE RELYING ON THIS. It is a DENYLIST, not an allowlist and
/// not a version comparison. The four tags named below are the engines known to
/// PREDATE the two fixes. EVERY other string returns true, including a tag this
/// app has never heard of.
///
/// For real engines that is the intended answer: anything cut after `v0.33.3`
/// contains both fixes, so defaulting unknown-newer to yes is correct and means
/// a future pin bump does not have to remember to edit this function.
///
/// The cost is that a WRONG tag also returns true. Verified by evaluating both
/// `matches!` arms: `"v0.34.9-typo"`, `"V0.33.2"` (wrong case) and `""` all
/// answer yes, because none of them is spelled like one of the four denied
/// tags. So this gate is not a defence against a garbled or mistaken tag. It
/// defends against exactly the four old engines it names and nothing else. If
/// the pin is ever set to a string that does not correspond to a real release,
/// a keeper conf goes out on whatever engine is actually installed.
///
/// The first `matches!` arm is redundant: `v0.33.3-pr105c` and `v0.33.3` are
/// absent from the denylist, so the second arm already admits them. It is kept
/// as a record of the first blessed tags, not as the thing doing the work.
pub fn engine_supports_keeper_profile(node_release_tag: &str) -> bool {
    // v0.33.3-pr105c (btxd 1932613f + anchor memo) is the first blessed tag:
    // it contains 1d73e70b and 0ece8ef4, the two fixes the gate exists for.
    matches!(node_release_tag, "v0.33.3-pr105c" | "v0.33.3")
        || !matches!(
            node_release_tag,
            "v0.33.3-pr105b" | "v0.33.2" | "v0.33.1" | "v0.33.0"
        )
}

/// Select the faststart conf for a profile, applying the engine gate. A keeper
/// CHOICE on one of the four denied engines provisions the safe full-node conf
/// instead, and the UI tells the user their choice activates with the next
/// engine update.
///
/// The strength of that gate is the strength of `engine_supports_keeper_profile`,
/// which is a denylist. Every tag outside those four gets the keeper conf, so
/// this function screens out the known-old engines. It does not verify that the
/// installed engine is a real release, and a mistyped pin passes.
pub fn conf_for_profile(profile: &str, node_release_tag: &str) -> &'static str {
    if profile == "keeper" && engine_supports_keeper_profile(node_release_tag) {
        NODE_KEEPER_CONF
    } else {
        NODE_FASTSTART_CONF
    }
}

/// Resolve the directory holding the bundled node binaries (`resources/node-bin/`).
/// In a packaged app Tauri copies `resources/node-bin/*` under the resource dir;
/// in `tauri dev` we fall back to the consuming APP's own `resources/node-bin/`
/// (passed via `dev_roots`, typically `&[Path::new(env!("CARGO_MANIFEST_DIR"))]`
/// evaluated in the app crate — btx-core is a library and has no resources of
/// its own). Returns `None` (so the caller falls back to the python installer)
/// when no `btxd` is found in any candidate — e.g. a build that didn't bundle
/// the binaries.
pub fn resolve_bundled_node_bin(
    resource_dir: Option<&Path>,
    dev_roots: &[&Path],
) -> Option<PathBuf> {
    let mut candidates: Vec<PathBuf> = Vec::new();
    if let Some(res) = resource_dir {
        // Tauri's resource layout differs across versions/platforms: some place
        // declared `resources/node-bin/*` directly under the resource dir, others
        // preserve the leading `resources/`. Check BOTH so a real bundle never
        // silently falls back to the python installer (which can't run on a clean
        // Mac). This mirrors the two conventions already seen in this codebase
        // (resolve_faststart_script vs resolve_solver_bin).
        candidates.push(res.join("node-bin"));
        candidates.push(res.join("resources").join("node-bin"));
    }
    for root in dev_roots {
        candidates.push(root.join("resources").join("node-bin"));
    }
    // The daemon's filename carries the platform exe suffix (btxd vs btxd.exe).
    // Probing the bare "btxd" silently misses a real Windows bundle and falls
    // back to the (mac-only) python installer — so resolve via exe_name().
    let btxd_name = crate::platform::exe_name("btxd");
    candidates.into_iter().find(|p| p.join(&btxd_name).exists())
}

/// Self-contained, dependency-free provisioning: copy the bundled node binaries
/// into the deterministic install dir, make them executable + ad-hoc sign them
/// (so macOS doesn't SIGKILL an unsigned Mach-O), and write the miner conf.
///
/// This produces the SAME `FaststartResult` the python installer would, so the
/// rest of `first_run_setup` (node start, `ensure_snapshot_loaded`, mining) is
/// unchanged — but with NO runtime dependency on system `python3` or `gpg`. Trust
/// comes from the binaries shipping INSIDE the distributed app, not a runtime
/// download + GPG check.
pub fn provision_from_bundle(
    bundled_bin_dir: &Path,
    release_tag: &str,
    datadir: &Path,
) -> AppResult<FaststartResult> {
    let install_bin = install_dir(release_tag)
        .ok_or_else(|| AppError::Config("HOME unset; cannot resolve install dir".into()))?
        .join("bin");
    std::fs::create_dir_all(&install_bin).map_err(|e| {
        AppError::Process(format!("create install dir {}: {e}", install_bin.display()))
    })?;

    for name in BUNDLED_NODE_BINARIES {
        // Bundled filenames carry the platform exe suffix (btxd vs btxd.exe), so
        // resolve both the source and destination through exe_name().
        let fname = crate::platform::exe_name(name);
        let src = bundled_bin_dir.join(&fname);
        if !src.exists() {
            if *name == "btxd" || *name == "btx-cli" {
                return Err(AppError::Config(format!(
                    "bundled binary missing: {fname} (looked in {})",
                    bundled_bin_dir.display()
                )));
            }
            // Best-effort tool — skip it.
            continue;
        }
        let dst = install_bin.join(&fname);
        std::fs::copy(&src, &dst).map_err(|e| AppError::Process(format!("copy {fname}: {e}")))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(&dst, std::fs::Permissions::from_mode(0o755));
        }
        // Re-sign on THIS machine so the kernel accepts the exec (matches what the
        // python installer + NodeController do for downloaded binaries).
        crate::node::ensure_adhoc_signed(&dst, datadir);
    }

    // Write the miner faststart.conf (bootstrap peers appended by the caller).
    let faststart_dir = datadir.join("faststart");
    std::fs::create_dir_all(&faststart_dir)
        .map_err(|e| AppError::Process(format!("create faststart dir: {e}")))?;
    let conf_path = faststart_dir.join("faststart.conf");
    std::fs::write(&conf_path, MINER_FASTSTART_CONF)
        .map_err(|e| AppError::Process(format!("write faststart.conf: {e}")))?;

    Ok(FaststartResult {
        btxd: install_bin.join(crate::platform::exe_name("btxd")),
        btx_cli: install_bin.join(crate::platform::exe_name("btx-cli")),
        faststart_conf: conf_path,
        mining_results_dir: None,
    })
}

/// Absolute install directory a given `release_tag`'s binaries live under:
/// `~/.local/btx/<release_tag>/<platform_id>/`. Returns `None` if `$HOME` is
/// unset. Mirrors `returning_launch_paths`' layout so the Settings panel can
/// size the install on disk.
pub fn install_dir(release_tag: &str) -> Option<PathBuf> {
    let home = crate::platform::home_dir()?;
    Some(
        home.join(".local")
            .join("btx")
            .join(release_tag)
            .join(platform_id()),
    )
}

/// Platform id string matching `btx-agent-setup.py`'s `detect_platform_id`.
pub fn platform_id() -> &'static str {
    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    {
        "macos-arm64"
    }
    #[cfg(all(target_os = "macos", target_arch = "x86_64"))]
    {
        "macos-x86_64"
    }
    #[cfg(all(target_os = "linux", target_arch = "x86_64"))]
    {
        "linux-x86_64"
    }
    #[cfg(all(target_os = "linux", target_arch = "aarch64"))]
    {
        "linux-arm64"
    }
    #[cfg(all(target_os = "windows", target_arch = "x86_64"))]
    {
        "windows-x86_64"
    }
    #[cfg(not(any(
        all(target_os = "macos", target_arch = "aarch64"),
        all(target_os = "macos", target_arch = "x86_64"),
        all(target_os = "linux", target_arch = "x86_64"),
        all(target_os = "linux", target_arch = "aarch64"),
        all(target_os = "windows", target_arch = "x86_64"),
    )))]
    {
        "unknown"
    }
}

/// Recursively find the first file named `name` under `dir` (mirrors the
/// installer's `find_binary` rglob+sorted behaviour). Shallow, dependency-free
/// walk; returns the lexicographically-first match for determinism.
fn find_binary(dir: &Path, name: &str) -> Option<PathBuf> {
    let mut matches: Vec<PathBuf> = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        // Skip unreadable directories rather than aborting the whole walk.
        let Ok(entries) = std::fs::read_dir(&d) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.file_name().and_then(|n| n.to_str()) == Some(name) {
                matches.push(path);
            }
        }
    }
    matches.sort();
    matches.into_iter().next()
}

/// Resolve the absolute path to the bundled `btx-agent-setup.py`.
///
/// Resolution order (first existing wins):
///   1. **Bundled app** — `<resource_dir>/faststart/btx-agent-setup.py`.
///      Tauri copies `resources/faststart/*` next to the binary, and
///      `resource_dir` points at that location in a packaged build.
///   2. **`tauri dev`** — `resource_dir` is unreliable in dev, so fall back to
///      the crate's own `resources/faststart/` via `CARGO_MANIFEST_DIR` (baked
///      in at compile time = `src-tauri/`).
///   3. **Repo source** — the upstream `contrib/faststart/` copy, as a last
///      resort for running from a checkout without a bundled resource.
///
/// The bundled `btx-agent-setup.py` execs `btx-faststart.py` from its own
/// directory (`SCRIPT_DIR / "btx-faststart.py"`), so as long as both scripts
/// live in the SAME resolved directory the sibling exec just works.
pub fn resolve_faststart_script(
    resource_dir: Option<&Path>,
    dev_roots: &[&Path],
) -> AppResult<PathBuf> {
    let mut candidates: Vec<PathBuf> = Vec::new();

    // 1. Bundled resource dir (packaged app).
    if let Some(res) = resource_dir {
        candidates.push(res.join("faststart").join(FASTSTART_ENTRY_SCRIPT));
    }
    // 2. Dev: the consuming APP's resources dir (its CARGO_MANIFEST_DIR — the
    //    env! macro must be evaluated in the app crate, not in this library).
    for root in dev_roots {
        candidates.push(
            root.join("resources")
                .join("faststart")
                .join(FASTSTART_ENTRY_SCRIPT),
        );
        // 3. Repo source checkout (sibling btx-main at the workspace root).
        if let Some(repo_parent) = root.parent().and_then(|p| p.parent()) {
            candidates.push(
                repo_parent
                    .join("btx-main")
                    .join("contrib")
                    .join("faststart")
                    .join(FASTSTART_ENTRY_SCRIPT),
            );
        }
    }

    candidates
        .iter()
        .find(|p| p.exists())
        .cloned()
        .ok_or_else(|| {
            AppError::Config(format!(
                "could not locate bundled {FASTSTART_ENTRY_SCRIPT}; looked in: {}",
                candidates
                    .iter()
                    .map(|p| p.display().to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            ))
        })
}

/// Import the bundled BTX release public key into the process-local gpg keyring.
///
/// This must be called BEFORE `run_faststart` so that `gpg --verify` inside the
/// installer subprocess can find the key. `gpg --import` is idempotent: re-importing
/// an already-present key exits 0, so calling this on every first-run is safe.
pub fn import_release_key(
    runner: &dyn CommandRunner,
    gpg_bin: &str,
    key_path: &Path,
) -> AppResult<()> {
    let out = runner
        .run(
            gpg_bin,
            &["--import".to_string(), key_path.display().to_string()],
            &[],
        )
        .map_err(|_| {
            AppError::Config(
                "GnuPG (gpg) is required to verify the BTX release. \
                 Install it (e.g. 'brew install gnupg') and retry."
                    .to_string(),
            )
        })?;

    if !out.status.success() {
        return Err(AppError::Process(format!(
            "gpg --import failed: {}",
            String::from_utf8_lossy(&out.stderr)
        )));
    }

    Ok(())
}

/// Per-asset SHA-256 pins for upstream release tags that shipped WITHOUT a GPG
/// signature (`btx-release-manifest.json` → `"signature_file": null`), keyed by
/// tag via [`unsigned_release_pins`].
///
/// v0.33.3 (the 191,714 ASERT-dump-floor hard fork, published 2026-08-17T15:19Z
/// from commit 6053ef71) is a native cut whose release notes state outright that
/// it is not GPG-signed and that `btx-agent-setup.py` needs
/// `--allow-unsigned-release`. Passing that flag alone would shift trust to the
/// channel-served SHA256SUMS; these compiled-in digests are the compensating
/// control. They were measured 2026-08-17 from the release API AND re-verified
/// by downloading the assets and hashing them locally; the installer script
/// enforces them against SHA256SUMS before anything is downloaded or installed.
///
/// The set is exactly the assets whose CONTENT an install consumes: the three
/// platform archives plus `snapshot.manifest.json` (which transitively pins
/// `snapshot.dat` — btx-faststart.py verifies the snapshot download against the
/// sha256 recorded inside the manifest). Metadata assets (release manifest,
/// README, source tarball) are deliberately unpinned: with the consumed assets
/// pinned they cannot influence what ends up installed, and pinning them would
/// only make an in-place metadata re-upload brick installs of still-authentic
/// binaries.
pub const V0_33_3_UNSIGNED_PINS: &[(&str, &str)] = &[
    (
        "btx-0.33.3-arm64-apple-darwin.tar.gz",
        "a4a632bb55dafe3bf00ba196d8fa5d2fb941296b05e6924ffd5e24a4c989445d",
    ),
    (
        "btx-0.33.3-x86_64-linux-gnu.tar.gz",
        "317e0f3c26ea7cba7a76ea050aae570ea3b8eef79623afe76e41f3713e416aef",
    ),
    (
        "btx-0.33.3-x86_64-linux-gnu-cuda13.tar.gz",
        "f099099691268da51f5492527a94b3d078f05c48404ffc37f56a927ec06f13be",
    ),
    (
        "snapshot.manifest.json",
        "2eb9591b17d142f4c88741e39f7ebac3dff1036d52eaf9bc6892510d9cd3714d",
    ),
];

/// The compiled-in pin set for `release_tag`, or `None` when we have none.
///
/// `None` means [`run_faststart`] runs in its default signed mode: the installer
/// script requires a GPG signature from the pinned BTX release key and fails
/// closed otherwise. Every unsigned upstream cut we want installable therefore
/// needs a measured pin set added HERE, in a reviewed release of this app — an
/// unknown future unsigned tag stays uninstallable by construction.
pub fn unsigned_release_pins(release_tag: &str) -> Option<&'static [(&'static str, &'static str)]> {
    match release_tag {
        "v0.33.3" => Some(V0_33_3_UNSIGNED_PINS),
        _ => None,
    }
}

/// Runs the official `btx-agent-setup.py --preset miner ... --json` and parses
/// the machine-readable summary (keys: btxd, btx_cli, faststart_conf, mining_results_dir).
///
/// SECURITY — two trust modes, both fail closed (non-zero exit is the boundary):
///   * `unsigned_pins: None` (default): `--allow-unsigned-release` is NOT passed.
///     The installer requires SHA256SUMS to be GPG-signed by the pinned BTX
///     release key and refuses unsigned releases outright.
///   * `unsigned_pins: Some(pins)`: for release tags we KNOW shipped unsigned
///     (see [`unsigned_release_pins`]), `--allow-unsigned-release` is passed
///     together with `--pin-sha256 NAME=DIGEST` for every pinned asset. The
///     script then requires SHA256SUMS to match the compiled-in digests before
///     anything is downloaded, and requires the consumed assets (platform
///     archive + snapshot manifest) to be among the pins — the pins replace the
///     missing GPG signature as the trust anchor. An empty or malformed pin set
///     is rejected HERE, before the installer is even invoked: the flag must
///     never reach the script without enforceable pins beside it.
pub fn run_faststart(
    runner: &dyn CommandRunner,
    python: &str,
    script: &str,
    repo: &str,
    release_tag: &str,
    datadir: &str,
    log_path: Option<&Path>,
    unsigned_pins: Option<&[(&str, &str)]>,
) -> AppResult<FaststartResult> {
    // Validate pins BEFORE any subprocess: --allow-unsigned-release without an
    // enforceable pin set must be unrepresentable, not merely unlikely.
    if let Some(pins) = unsigned_pins {
        if pins.is_empty() {
            return Err(AppError::Config(
                "unsigned-release install requested with an empty sha256 pin set — refusing \
                 (--allow-unsigned-release is only ever passed alongside compiled-in pins)"
                    .to_string(),
            ));
        }
        for (name, digest) in pins {
            if digest.len() != 64 || !digest.chars().all(|c| c.is_ascii_hexdigit()) {
                return Err(AppError::Config(format!(
                    "invalid compiled-in sha256 pin for {name}: expected 64 hex chars"
                )));
            }
        }
    }
    // Security addendum 4: detect python3 first, before invoking the installer.
    // macOS 12.3+ ships no python3 by default; fail with a clear remediation message.
    let py_check = runner
        .run(python, &["--version".to_string()], &[])
        .map_err(|_| {
            AppError::Config(
                "python3 is required but was not found. Install Python 3 and retry.".to_string(),
            )
        })?;
    if !py_check.status.success() {
        return Err(AppError::Config(
            "python3 is required but was not found. Install Python 3 and retry.".to_string(),
        ));
    }

    // NOTE: --allow-unsigned-release appears ONLY when compiled-in pins ride
    // along with it (validated above). Without pins the installer verifies GPG
    // signatures and SHA256SUMS; a non-zero exit means verification failed and
    // we must propagate that as an error (fail closed).
    let mut args: Vec<String> = vec![
        script.into(),
        "--repo".into(),
        repo.into(),
        "--release-tag".into(),
        release_tag.into(),
        "--preset".into(),
        "miner".into(),
        "--datadir".into(),
        datadir.into(),
        "--json".into(),
    ];
    if let Some(pins) = unsigned_pins {
        args.push("--allow-unsigned-release".into());
        for (name, digest) in pins {
            args.push("--pin-sha256".into());
            args.push(format!("{name}={}", digest.to_ascii_lowercase()));
        }
    }
    let out = runner
        .run(python, &args, &[])
        .map_err(|e| AppError::Process(e.to_string()))?;

    // Log capture: persist the installer's stdout/stderr to <datadir>/
    // easybtx-install.log so the in-app "see logs in ~/.easybtx" copy is
    // truthful and so install failures are diagnosable post-mortem. Best-effort:
    // a logging failure must never block setup.
    if let Some(log) = log_path {
        if let Some(parent) = log.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        let mut buf = Vec::with_capacity(out.stdout.len() + out.stderr.len() + 32);
        buf.extend_from_slice(b"===== stdout =====\n");
        buf.extend_from_slice(&out.stdout);
        buf.extend_from_slice(b"\n===== stderr =====\n");
        buf.extend_from_slice(&out.stderr);
        if let Err(e) = std::fs::write(log, &buf) {
            eprintln!(
                "[installer] could not write install log {}: {e}",
                log.display()
            );
        }
    }

    // Security addendum 2: fail closed on non-zero exit (signature/SHA failure propagates here).
    if !out.status.success() {
        return Err(AppError::Process(format!(
            "faststart exited non-zero: {}",
            String::from_utf8_lossy(&out.stderr)
        )));
    }

    let v: Value =
        serde_json::from_slice(&out.stdout).map_err(|e| AppError::Decode(e.to_string()))?;

    // Security addendum 3 (best-effort verification assertion):
    // If the installer JSON contains a boolean verification flag, require it to be true.
    // We check `verified`, `signature_verified`, and `release_verified` in that order.
    // If NONE of these keys are present, we do NOT fabricate a failure — we rely on
    // the fail-closed non-zero exit (addenda 1+2) as the primary trust signal.
    // This is best-effort: the installer may not emit such a key at all.
    for flag_key in &["verified", "signature_verified", "release_verified"] {
        if let Some(val) = v.get(flag_key) {
            if let Some(b) = val.as_bool() {
                if !b {
                    return Err(AppError::Process(format!(
                        "installer reported verification failure: {}=false",
                        flag_key
                    )));
                }
            }
        }
    }

    let path = |k: &str| -> AppResult<PathBuf> {
        v.get(k)
            .and_then(|x| x.as_str())
            .map(PathBuf::from)
            .ok_or_else(|| AppError::Decode(format!("missing key '{k}' in faststart json")))
    };
    Ok(FaststartResult {
        btxd: path("btxd")?,
        btx_cli: path("btx_cli")?,
        faststart_conf: path("faststart_conf")?,
        mining_results_dir: v
            .get("mining_results_dir")
            .and_then(|x| x.as_str())
            .map(PathBuf::from),
    })
}

/// Resolve the directory holding a bundled node PACKAGE tree
/// (`resources/node-pkg/` → `bin/` wrappers + `libexec/*.real` + metal libs),
/// the layout BTX ships from v0.32.12 onward. Mirrors
/// [`resolve_bundled_node_bin`] but probes `bin/btxd` inside the package root.
pub fn resolve_bundled_node_pkg(
    resource_dir: Option<&Path>,
    dev_roots: &[&Path],
) -> Option<PathBuf> {
    let mut candidates: Vec<PathBuf> = Vec::new();
    if let Some(res) = resource_dir {
        candidates.push(res.join("node-pkg"));
        candidates.push(res.join("resources").join("node-pkg"));
    }
    for root in dev_roots {
        candidates.push(root.join("resources").join("node-pkg"));
    }
    let btxd_name = crate::platform::exe_name("btxd");
    candidates
        .into_iter()
        .find(|p| p.join("bin").join(&btxd_name).exists())
}

/// Whether the file at `path` starts with a Mach-O magic (thin, 64-bit, or fat,
/// either endianness). Used to decide what to ad-hoc re-sign inside a node
/// package: the v0.32.12 `bin/` wrappers are scripts (codesign would just
/// error) while `libexec/*.real` are the actual Mach-O daemons macOS SIGKILLs
/// without a locally-acceptable signature. Best-effort: unreadable → false.
fn is_macho(path: &Path) -> bool {
    use std::io::Read;
    let Ok(mut f) = std::fs::File::open(path) else {
        return false;
    };
    let mut magic = [0u8; 4];
    if f.read_exact(&mut magic).is_err() {
        return false;
    }
    matches!(
        u32::from_be_bytes(magic),
        0xfeed_face | 0xfeed_facf | 0xcefa_edfe | 0xcffa_edfe | 0xcafe_babe | 0xbeba_feca
    )
}

/// Recursively copy the directory tree at `src` into `dst` (created as needed).
/// Follows the package layout as-is; symlinks are copied as their target's
/// contents (std::fs::copy semantics), which is fine for BTX release trees
/// (they contain none).
fn copy_tree(src: &Path, dst: &Path) -> AppResult<()> {
    std::fs::create_dir_all(dst)
        .map_err(|e| AppError::Process(format!("create dir {}: {e}", dst.display())))?;
    let entries = std::fs::read_dir(src)
        .map_err(|e| AppError::Process(format!("read dir {}: {e}", src.display())))?;
    for entry in entries.flatten() {
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if from.is_dir() {
            copy_tree(&from, &to)?;
        } else {
            std::fs::copy(&from, &to)
                .map_err(|e| AppError::Process(format!("copy {}: {e}", from.display())))?;
        }
    }
    Ok(())
}

/// Self-contained provisioning for a WHOLE node package tree (v0.32.12+ layout:
/// `bin/` launcher wrappers + `libexec/*.real` Mach-O daemons + metal shader
/// libs). Copies the tree into `install_root` (the caller computes it via
/// [`install_dir`]), marks everything under `bin/` and `libexec/` executable,
/// ad-hoc re-signs every Mach-O so the kernel accepts the exec (the wrapper
/// scripts are skipped — codesign can't sign a shell script), and writes
/// `conf_contents` as the faststart conf.
///
/// Produces the same [`FaststartResult`] shape as [`provision_from_bundle`], so
/// the rest of a setup pipeline (node start, `ensure_snapshot_loaded`) is
/// identical across package layouts.
/// Optional file inside a staged node package naming the btxd version it
/// carries (e.g. `v0.33.2`), for when that differs from the install tag.
/// Written by the staging scripts; absent packages fall back to the tag.
pub const BTXD_VERSION_MARKER: &str = ".btxd-version";

/// The release tag an install root encodes, i.e. the `vX.Y.Z` component of
/// `…/btx/<tag>/<platform>`. `None` for any layout without one — callers then
/// skip the version assert rather than inventing an expectation.
fn release_tag_from_install_root(install_root: &Path) -> Option<String> {
    let comps: Vec<&str> = install_root
        .components()
        .filter_map(|c| c.as_os_str().to_str())
        .collect();
    let i = comps.iter().rposition(|&c| c == "btx")?;
    comps
        .get(i + 1)
        .filter(|s| s.starts_with('v'))
        .map(|s| (*s).to_string())
}

/// Whether `btxd --version` output belongs to `tag`.
///
/// btxd prints `BTX daemon version v0.33.2` (verified against the shipped
/// binary). Matching on a bounded token rather than a bare `contains` keeps
/// `v0.33.1` from satisfying a `v0.33.11` expectation, and vice versa. Pure →
/// unit-tested.
pub fn version_output_matches_tag(output: &str, tag: &str) -> bool {
    let tag = tag.trim();
    if tag.is_empty() {
        return false;
    }
    output
        .split(|c: char| !(c.is_ascii_alphanumeric() || c == '.'))
        .any(|tok| tok == tag)
}

/// Execute the staged btxd and confirm it reports `expected_tag`.
fn verify_btxd_reports_tag(btxd: &Path, expected_tag: &str) -> AppResult<()> {
    let mut cmd = std::process::Command::new(btxd);
    cmd.arg("--version");
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        cmd.creation_flags(0x0800_0000); // CREATE_NO_WINDOW
    }
    let out = cmd.output().map_err(|e| {
        AppError::Process(format!(
            "staged btxd at {} could not be executed: {e}",
            btxd.display()
        ))
    })?;
    // btxd writes its banner to stdout; keep stderr in play so a wrapper that
    // reports there is still understood.
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    if version_output_matches_tag(&text, expected_tag) {
        return Ok(());
    }
    Err(AppError::Config(format!(
        "staged node package is not {expected_tag}: `btxd --version` reported {:?}. \
         Re-stage the bundle (scripts/stage-node-pkg*.sh) against {expected_tag}.",
        text.lines().next().unwrap_or("").trim()
    )))
}

pub fn provision_node_package(
    bundled_pkg_dir: &Path,
    install_root: &Path,
    datadir: &Path,
    conf_contents: &str,
) -> AppResult<FaststartResult> {
    let btxd_name = crate::platform::exe_name("btxd");
    if !bundled_pkg_dir.join("bin").join(&btxd_name).exists() {
        return Err(AppError::Config(format!(
            "bundled node package missing bin/{btxd_name} (looked in {})",
            bundled_pkg_dir.display()
        )));
    }

    copy_tree(bundled_pkg_dir, install_root)?;

    // Exec bits + ad-hoc signature. bin/ holds the launcher wrappers, libexec/
    // the real daemons; both need +x. Only genuine Mach-Os get re-signed (the
    // kernel only SIGKILLs Mach-Os; signing a script is an error, not a no-op).
    for sub in ["bin", "libexec"] {
        let dir = install_root.join(sub);
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let p = entry.path();
            if !p.is_file() {
                continue; // e.g. libexec/metal/ shader dir — data, not executables
            }
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let _ = std::fs::set_permissions(&p, std::fs::Permissions::from_mode(0o755));
            }
            if is_macho(&p) {
                crate::node::ensure_adhoc_signed(&p, datadir);
            }
        }
    }

    // The installed tree must actually BE the release its directory claims.
    //
    // This matters far beyond tidiness: `node::build_node_command` decides
    // whether to pass version-gated flags (`-autoupdate`, and since the MatMul
    // v4.7 fork `-matmulrcexecution`) by parsing the release tag out of the
    // INSTALL PATH, and that path is minted from `NODE_RELEASE_TAG`. So a stale
    // bundle staged under a newer tag's directory would make us hand
    // `-matmulrcexecution=auto-fallback` to a v0.33.1 btxd, which rejects
    // unknown args FATALLY — turning "the node stalls at the fork" into "the
    // node never starts at all". Verified: v0.33.1 exits with
    // `Error parsing command line arguments: Invalid parameter
    // -matmulrcexecution=auto-fallback`.
    //
    // Asking the binary closes that gap at the only moment it can be closed
    // cheaply, once per provision rather than once per launch. A btxd that
    // cannot be executed, or that does not report the expected tag, makes this
    // function return Err.
    //
    // That is a refusal, NOT a rollback. `copy_tree` above has already run by
    // the time the check fails, so the rejected tree is sitting complete under
    // `install_root` and nothing here removes it. What keeps the previous
    // install intact is the layout, not this check: install roots are keyed by
    // tag (`~/.local/btx/<tag>/<platform>`), so a failed provision of a new tag
    // never writes over the old tag's directory. The caller does the rest by
    // logging the failure and launching the old tag.
    // A package MAY declare which btxd version it actually carries, in
    // `.btxd-version`. That exists because an upstream branch build can be
    // newer than any tag while still reporting the OLD version: BTX's
    // `pr/0.33.3-network-stability` never bumped CLIENT_VERSION_BUILD, so a
    // build of it reports `v0.33.2`. We still need our own install tag to move
    // (nothing re-provisions otherwise), so the tag and the reported version
    // legitimately differ — and the check has to compare against what the
    // package says it holds, not against the directory name.
    //
    // ⚠ Do NOT "fix" that by patching the version in BTX's source. btxd embeds
    // whether its source tree was dirty and fails its own production canary
    // with `build_provenance_mismatch` if it was, leaving a node that runs and
    // syncs but silently refuses to validate. Measured: bumping one line in
    // CMakeLists.txt took a passing canary to `ready=0`.
    //
    // Packages without the marker keep the old behaviour: verify against the
    // install-root tag.
    let expected = expected_btxd_version(bundled_pkg_dir, install_root);
    if let Some(expected) = expected {
        let btxd_path = install_root.join("bin").join(&btxd_name);
        verify_btxd_reports_tag(&btxd_path, &expected)?;
    }

    // Write the node faststart.conf (bootstrap peers appended by the caller via
    // `setup::ensure_addnodes_in_conf`, mirroring the miner flow).
    let faststart_dir = datadir.join("faststart");
    std::fs::create_dir_all(&faststart_dir)
        .map_err(|e| AppError::Process(format!("create faststart dir: {e}")))?;
    let conf_path = faststart_dir.join("faststart.conf");
    std::fs::write(&conf_path, conf_contents)
        .map_err(|e| AppError::Process(format!("write faststart.conf: {e}")))?;

    Ok(FaststartResult {
        btxd: install_root.join("bin").join(&btxd_name),
        btx_cli: install_root
            .join("bin")
            .join(crate::platform::exe_name("btx-cli")),
        faststart_conf: conf_path,
        mining_results_dir: None,
    })
}

/// Which btxd version this package claims to carry, and therefore what the
/// staged binary must report: the `.btxd-version` marker if the package has a
/// usable one, else the tag in the install root.
///
/// Split out of `provision_node_package` so the precedence is testable without
/// executing a binary. It had NO coverage — both provision tests use tag-less
/// install roots, so `expected` was always `None` and the gate was never
/// entered — while in production `install_dir` always builds `.../btx/<tag>/…`
/// and therefore always yields an expectation. A future edit to this precedence
/// would have landed green.
///
/// An EMPTY marker falls through to the tag rather than expecting `""`. That is
/// a real staging failure mode, not a hypothetical: three staging scripts wrote
/// the marker through a pipeline that could not fail, so a btxd that would not
/// run produced an empty file and the package shipped.
fn expected_btxd_version(bundled_pkg_dir: &Path, install_root: &Path) -> Option<String> {
    std::fs::read_to_string(bundled_pkg_dir.join(BTXD_VERSION_MARKER))
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .or_else(|| release_tag_from_install_root(install_root))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::CommandRunner;
    use std::process::{ExitStatus, Output};

    #[test]
    fn version_output_matches_only_the_exact_tag() {
        // Verbatim banner from the shipped v0.33.2 darwin binary.
        let real = "BTX daemon version v0.33.2\nCopyright (C) 2009-2026 The BTX developers";
        assert!(version_output_matches_tag(real, "v0.33.2"));

        // The whole point: a near-miss must NOT satisfy the expectation, or the
        // fatal-flag landmine reopens.
        assert!(!version_output_matches_tag(real, "v0.33.1"));
        assert!(!version_output_matches_tag(
            "BTX daemon version v0.33.1",
            "v0.33.2"
        ));
        // Prefix collisions in BOTH directions (`contains` would pass these).
        assert!(!version_output_matches_tag(
            "BTX daemon version v0.33.11",
            "v0.33.1"
        ));
        assert!(!version_output_matches_tag(
            "BTX daemon version v0.33.1",
            "v0.33.11"
        ));
        // Degenerate input never counts as a match.
        assert!(!version_output_matches_tag(real, ""));
        assert!(!version_output_matches_tag("", "v0.33.2"));
    }

    #[test]
    fn the_marker_outranks_the_tag_and_an_empty_marker_falls_back() {
        let pkg = tempfile::tempdir().unwrap();
        let root = Path::new("/h/.local/btx/v0.34.5/linux-x86_64");

        // No marker at all: fall back to the install-root tag.
        assert_eq!(
            expected_btxd_version(pkg.path(), root).as_deref(),
            Some("v0.34.5")
        );

        // A marker WINS over the tag. Branch builds legitimately differ: BTX's
        // 0.33.3 PR never bumped CLIENT_VERSION_BUILD, so the binary reports a
        // version the install tag does not match, and the marker is the truth.
        std::fs::write(
            pkg.path().join(BTXD_VERSION_MARKER),
            "v0.34.6
",
        )
        .unwrap();
        assert_eq!(
            expected_btxd_version(pkg.path(), root).as_deref(),
            Some("v0.34.6")
        );

        // A four-segment reseal tag survives intact — the case three staging
        // scripts used to truncate to three segments.
        std::fs::write(pkg.path().join(BTXD_VERSION_MARKER), "v0.33.4.1").unwrap();
        assert_eq!(
            expected_btxd_version(pkg.path(), root).as_deref(),
            Some("v0.33.4.1")
        );

        // An EMPTY or whitespace-only marker is a staging failure, not an
        // expectation of "": fall back rather than demanding the binary report
        // an empty version, which nothing can satisfy.
        for junk in [
            "", "   ", "

",
        ] {
            std::fs::write(pkg.path().join(BTXD_VERSION_MARKER), junk).unwrap();
            assert_eq!(
                expected_btxd_version(pkg.path(), root).as_deref(),
                Some("v0.34.5"),
                "empty marker {junk:?} must fall back to the tag"
            );
        }

        // Neither a usable marker nor a tagged root: skip the assert rather
        // than invent an expectation.
        std::fs::write(pkg.path().join(BTXD_VERSION_MARKER), "").unwrap();
        assert_eq!(
            expected_btxd_version(pkg.path(), Path::new("/opt/node")),
            None
        );
    }

    #[test]
    fn release_tag_is_read_from_the_install_root_or_skipped() {
        assert_eq!(
            release_tag_from_install_root(Path::new("/h/.local/btx/v0.33.2/mac")).as_deref(),
            Some("v0.33.2")
        );
        // No `btx/<tag>` layout → None, so provisioning skips the assert rather
        // than inventing an expectation it cannot justify.
        assert_eq!(release_tag_from_install_root(Path::new("/opt/node")), None);
        // A component that isn't a version tag is not treated as one.
        assert_eq!(
            release_tag_from_install_root(Path::new("/h/btx/current/mac")),
            None
        );
    }

    /// Cross-platform fake `ExitStatus` for the given exit code (see the same
    /// helper in backend.rs): unix takes a raw wait-status (`code << 8`), windows
    /// takes the code directly. Lets the mock runner compile on Windows CI too.
    fn fake_status(code: u32) -> ExitStatus {
        #[cfg(unix)]
        {
            use std::os::unix::process::ExitStatusExt;
            ExitStatus::from_raw((code << 8) as i32)
        }
        #[cfg(windows)]
        {
            use std::os::windows::process::ExitStatusExt;
            ExitStatus::from_raw(code)
        }
    }

    /// FakeRunner that can serve different responses for the python-version check
    /// vs the installer invocation, by inspecting the args slice. Records every
    /// invocation's args so tests can assert on the security-relevant flags
    /// (`--allow-unsigned-release` / `--pin-sha256`) actually passed.
    struct FakeRunner {
        /// Response when program is called with args[0] == "--version"
        py_version_ok: bool,
        /// stdout to return for the installer call
        installer_stdout: Vec<u8>,
        /// Whether the installer call succeeds (exit 0)
        installer_ok: bool,
        /// Args of every `run` invocation, in order. Mutex (not RefCell)
        /// because `CommandRunner: Send + Sync`.
        calls: std::sync::Mutex<Vec<Vec<String>>>,
    }

    impl FakeRunner {
        fn new(py_version_ok: bool, installer_ok: bool, installer_stdout: &[u8]) -> Self {
            Self {
                py_version_ok,
                installer_stdout: installer_stdout.to_vec(),
                installer_ok,
                calls: std::sync::Mutex::new(Vec::new()),
            }
        }

        fn recorded_calls(&self) -> Vec<Vec<String>> {
            self.calls.lock().unwrap().clone()
        }

        /// Args of the installer invocation (the last recorded call).
        fn installer_args(&self) -> Vec<String> {
            self.recorded_calls().last().cloned().unwrap_or_default()
        }
    }

    impl CommandRunner for FakeRunner {
        fn run(
            &self,
            _program: &str,
            args: &[String],
            _envs: &[(String, String)],
        ) -> std::io::Result<Output> {
            self.calls.lock().unwrap().push(args.to_vec());
            // Distinguish python --version check from installer invocation by args[0].
            let is_py_version_check = args.first().map(|a| a == "--version").unwrap_or(false);
            if is_py_version_check {
                let code = if self.py_version_ok { 0 } else { 1 };
                return Ok(Output {
                    status: fake_status(code),
                    stdout: b"Python 3.11.0\n".to_vec(),
                    stderr: vec![],
                });
            }
            // Installer invocation
            let code = if self.installer_ok { 0 } else { 1 };
            Ok(Output {
                status: fake_status(code),
                stdout: self.installer_stdout.clone(),
                stderr: if self.installer_ok {
                    vec![]
                } else {
                    b"signature mismatch".to_vec()
                },
            })
        }
    }

    #[test]
    fn parses_faststart_json() {
        let json = br#"{"btxd":"/data/bin/btxd","btx_cli":"/data/bin/btx-cli","faststart_conf":"/data/btx.conf","mining_results_dir":"/data/mining-ops"}"#;
        let r = FakeRunner::new(true, true, json);
        let res = run_faststart(
            &r,
            "python3",
            "btx-agent-setup.py",
            "btxchain/btx",
            "v0.30.1",
            "/data",
            None,
            None,
        )
        .unwrap();
        assert_eq!(res.btxd, PathBuf::from("/data/bin/btxd"));
        assert_eq!(
            res.mining_results_dir,
            Some(PathBuf::from("/data/mining-ops"))
        );
    }

    #[test]
    fn signed_mode_never_passes_allow_unsigned() {
        // THE security invariant of the default mode: without compiled-in pins,
        // --allow-unsigned-release (and --pin-sha256) must not appear at all —
        // the installer's GPG verification stays the sole trust anchor.
        let json = br#"{"btxd":"/b","btx_cli":"/c","faststart_conf":"/f"}"#;
        let r = FakeRunner::new(true, true, json);
        run_faststart(
            &r,
            "python3",
            "s.py",
            "btxchain/btx",
            "v0.30.1",
            "/data",
            None,
            None,
        )
        .unwrap();
        let args = r.installer_args();
        assert!(
            !args.iter().any(|a| a == "--allow-unsigned-release"),
            "signed mode must not pass --allow-unsigned-release: {args:?}"
        );
        assert!(
            !args.iter().any(|a| a == "--pin-sha256"),
            "signed mode must not pass pins: {args:?}"
        );
    }

    #[test]
    fn pinned_mode_passes_allow_unsigned_with_pins() {
        let json = br#"{"btxd":"/b","btx_cli":"/c","faststart_conf":"/f"}"#;
        let r = FakeRunner::new(true, true, json);
        let pins: &[(&str, &str)] = &[(
            "btx-0.33.3-arm64-apple-darwin.tar.gz",
            // Mixed case in: must be passed lowercased.
            "A4A632BB55DAFE3BF00BA196D8FA5D2FB941296B05E6924FFD5E24A4C989445D",
        )];
        run_faststart(
            &r,
            "python3",
            "s.py",
            "btxchain/btx",
            "v0.33.3",
            "/data",
            None,
            Some(pins),
        )
        .unwrap();
        let args = r.installer_args();
        assert!(args.iter().any(|a| a == "--allow-unsigned-release"));
        let pin_arg = args
            .iter()
            .position(|a| a == "--pin-sha256")
            .map(|i| args[i + 1].clone())
            .expect("--pin-sha256 must be passed");
        assert_eq!(
            pin_arg,
            "btx-0.33.3-arm64-apple-darwin.tar.gz=a4a632bb55dafe3bf00ba196d8fa5d2fb941296b05e6924ffd5e24a4c989445d"
        );
    }

    #[test]
    fn empty_pin_set_fails_closed_before_any_subprocess() {
        // Some(&[]) must never degrade into a bare --allow-unsigned-release.
        let r = FakeRunner::new(true, true, b"{}");
        let result = run_faststart(
            &r,
            "python3",
            "s.py",
            "btxchain/btx",
            "v0.33.3",
            "/data",
            None,
            Some(&[]),
        );
        assert!(result.is_err(), "empty pin set must be rejected");
        assert!(
            r.recorded_calls().is_empty(),
            "no subprocess may run when the pin set is unusable"
        );
    }

    #[test]
    fn malformed_pin_digest_fails_closed_before_any_subprocess() {
        for bad in ["deadbeef", "", "zz", &"a".repeat(63), &"g".repeat(64)] {
            let r = FakeRunner::new(true, true, b"{}");
            let result = run_faststart(
                &r,
                "python3",
                "s.py",
                "btxchain/btx",
                "v0.33.3",
                "/data",
                None,
                Some(&[("asset.tar.gz", bad)]),
            );
            assert!(result.is_err(), "digest {bad:?} must be rejected");
            assert!(r.recorded_calls().is_empty());
        }
    }

    #[test]
    fn unsigned_pin_table_covers_exactly_v0_33_3() {
        // The one tag known to have shipped unsigned resolves to its pins…
        let pins = unsigned_release_pins("v0.33.3").expect("v0.33.3 must have pins");
        assert_eq!(pins.len(), 4, "three platform archives + snapshot manifest");
        let get = |name: &str| {
            pins.iter()
                .find(|(n, _)| *n == name)
                .map(|(_, d)| *d)
                .unwrap_or_else(|| panic!("{name} missing from pin table"))
        };
        // Digests measured 2026-08-17 from the release's SHA256SUMS AND
        // re-verified by downloading + hashing the assets themselves.
        assert_eq!(
            get("btx-0.33.3-arm64-apple-darwin.tar.gz"),
            "a4a632bb55dafe3bf00ba196d8fa5d2fb941296b05e6924ffd5e24a4c989445d"
        );
        assert_eq!(
            get("btx-0.33.3-x86_64-linux-gnu.tar.gz"),
            "317e0f3c26ea7cba7a76ea050aae570ea3b8eef79623afe76e41f3713e416aef"
        );
        assert_eq!(
            get("btx-0.33.3-x86_64-linux-gnu-cuda13.tar.gz"),
            "f099099691268da51f5492527a94b3d078f05c48404ffc37f56a927ec06f13be"
        );
        assert_eq!(
            get("snapshot.manifest.json"),
            "2eb9591b17d142f4c88741e39f7ebac3dff1036d52eaf9bc6892510d9cd3714d"
        );
        // …every pin is well-formed (the run_faststart gate would refuse it
        // otherwise, turning a table typo into an uninstallable release)…
        for (name, digest) in pins {
            assert_eq!(digest.len(), 64, "{name}: digest length");
            assert!(
                digest
                    .chars()
                    .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()),
                "{name}: digest must be lowercase hex"
            );
        }
        // …and every other tag has none: unknown unsigned cuts stay
        // uninstallable (fail closed on the missing signature) by construction.
        for other in [
            "v0.33.1",
            "v0.33.2",
            "v0.33.4",
            "v0.34.0",
            "",
            "v29.4.0-public-cli1",
        ] {
            assert!(
                unsigned_release_pins(other).is_none(),
                "{other} must have no pins"
            );
        }
    }

    #[test]
    fn errors_on_nonzero_exit() {
        let r = FakeRunner::new(true, false, b"");
        assert!(run_faststart(
            &r,
            "python3",
            "s.py",
            "btxchain/btx",
            "v0.30.1",
            "/data",
            None,
            None
        )
        .is_err());
    }

    #[test]
    fn rejects_when_verification_flag_false() {
        // Installer exits 0 but reports verified=false — must be rejected.
        let json = br#"{"btxd":"/b","btx_cli":"/c","faststart_conf":"/f","verified":false}"#;
        let r = FakeRunner::new(true, true, json);
        let result = run_faststart(
            &r,
            "python3",
            "s.py",
            "btxchain/btx",
            "v0.30.1",
            "/data",
            None,
            None,
        );
        assert!(
            result.is_err(),
            "expected Err when verified=false but got Ok"
        );
        let err_msg = result.unwrap_err().to_string();
        assert!(
            err_msg.contains("verification failure"),
            "error should mention verification failure, got: {err_msg}"
        );
    }

    #[test]
    fn writes_install_log_when_path_given() {
        let dir = tempfile::tempdir().unwrap();
        let log = dir.path().join("logs").join("easybtx-install.log");
        let json = br#"{"btxd":"/b","btx_cli":"/c","faststart_conf":"/f"}"#;
        let r = FakeRunner::new(true, true, json);
        run_faststart(
            &r,
            "python3",
            "btx-agent-setup.py",
            "btxchain/btx",
            "v0.30.1",
            "/data",
            Some(log.as_path()),
            None,
        )
        .unwrap();
        let contents = std::fs::read_to_string(&log).unwrap();
        assert!(contents.contains("===== stdout ====="));
        assert!(contents.contains("btxd"));
    }

    #[test]
    fn resolver_prefers_existing_resource_dir() {
        // A resource dir that actually contains the script wins over fallbacks.
        let dir = tempfile::tempdir().unwrap();
        let fs_dir = dir.path().join("faststart");
        std::fs::create_dir_all(&fs_dir).unwrap();
        let script = fs_dir.join(FASTSTART_ENTRY_SCRIPT);
        std::fs::write(&script, b"#!/usr/bin/env python3\n").unwrap();

        let resolved = resolve_faststart_script(Some(dir.path()), &[]).unwrap();
        assert_eq!(resolved, script);
    }

    #[test]
    fn resolver_falls_back_to_dev_root_resources() {
        // With no resource dir, the resolver must find the copy under a dev
        // root's resources/faststart/ (the consuming app passes its own
        // CARGO_MANIFEST_DIR as the dev root).
        let dir = tempfile::tempdir().unwrap();
        let fs_dir = dir.path().join("resources").join("faststart");
        std::fs::create_dir_all(&fs_dir).unwrap();
        let script = fs_dir.join(FASTSTART_ENTRY_SCRIPT);
        std::fs::write(&script, b"#!/usr/bin/env python3\n").unwrap();

        let resolved = resolve_faststart_script(None, &[dir.path()]).unwrap();
        assert_eq!(resolved, script);
    }

    #[test]
    fn resolver_errors_with_no_candidates() {
        // No resource dir and no dev roots → a clear Config error, never a panic.
        assert!(resolve_faststart_script(None, &[]).is_err());
    }

    // ── import_release_key tests ──────────────────────────────────────────────

    /// FakeRunner that simulates gpg --import behaviour.
    struct GpgFakeRunner {
        /// Whether gpg can be spawned at all (false = io::Error)
        can_spawn: bool,
        /// Exit code: 0 = success, 1 = failure
        exit_ok: bool,
    }

    impl CommandRunner for GpgFakeRunner {
        fn run(
            &self,
            _program: &str,
            _args: &[String],
            _envs: &[(String, String)],
        ) -> std::io::Result<Output> {
            if !self.can_spawn {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::NotFound,
                    "gpg not found",
                ));
            }
            let code = if self.exit_ok { 0 } else { 1 };
            Ok(Output {
                status: fake_status(code),
                stdout: vec![],
                stderr: if self.exit_ok {
                    vec![]
                } else {
                    b"gpg: keybox error".to_vec()
                },
            })
        }
    }

    #[test]
    fn import_release_key_success() {
        let r = GpgFakeRunner {
            can_spawn: true,
            exit_ok: true,
        };
        assert!(import_release_key(&r, "gpg", Path::new("/fake/BTX-RELEASE-PUBKEY.asc")).is_ok());
    }

    #[test]
    fn import_release_key_gpg_missing() {
        let r = GpgFakeRunner {
            can_spawn: false,
            exit_ok: false,
        };
        let result = import_release_key(&r, "gpg", Path::new("/fake/BTX-RELEASE-PUBKEY.asc"));
        assert!(result.is_err(), "expected Err when gpg not found");
        match result.unwrap_err() {
            AppError::Config(msg) => {
                assert!(
                    msg.contains("GnuPG (gpg) is required"),
                    "error should mention GnuPG, got: {msg}"
                );
            }
            other => panic!("expected AppError::Config, got: {other:?}"),
        }
    }

    #[test]
    fn import_release_key_nonzero_exit() {
        let r = GpgFakeRunner {
            can_spawn: true,
            exit_ok: false,
        };
        let result = import_release_key(&r, "gpg", Path::new("/fake/BTX-RELEASE-PUBKEY.asc"));
        assert!(result.is_err(), "expected Err on non-zero gpg exit");
        match result.unwrap_err() {
            AppError::Process(msg) => {
                assert!(
                    msg.contains("gpg --import failed"),
                    "error should mention gpg --import failed, got: {msg}"
                );
            }
            other => panic!("expected AppError::Process, got: {other:?}"),
        }
    }

    #[test]
    fn rejects_when_python_missing() {
        // python --version returns non-zero — must return Config error, never reach installer.
        let r = FakeRunner::new(false, true, b"irrelevant");
        let result = run_faststart(
            &r,
            "python3",
            "s.py",
            "btxchain/btx",
            "v0.30.1",
            "/data",
            None,
            None,
        );
        assert!(result.is_err(), "expected Err when python3 missing");
        match result.unwrap_err() {
            AppError::Config(msg) => {
                assert!(
                    msg.contains("python3 is required"),
                    "error should mention python3, got: {msg}"
                );
            }
            other => panic!("expected AppError::Config, got: {other:?}"),
        }
    }
    // ── provision_node_package (v0.32.12 wrapper+libexec tree) ──────────────

    /// Build a fake v0.32.12-style package tree: script wrappers in bin/, a
    /// fake Mach-O daemon in libexec/, and a metal shader dir that must be
    /// copied verbatim but never chmodded/signed.
    fn fake_node_pkg(root: &Path) {
        std::fs::create_dir_all(root.join("bin")).unwrap();
        std::fs::create_dir_all(root.join("libexec").join("metal")).unwrap();
        // Wrapper filenames carry the platform exe suffix (btxd vs btxd.exe) —
        // provision_node_package probes via exe_name(), so the fixture must too
        // or the test only passes on unix.
        std::fs::write(
            root.join("bin").join(crate::platform::exe_name("btxd")),
            b"#!/bin/sh\nexec real\n",
        )
        .unwrap();
        std::fs::write(
            root.join("bin").join(crate::platform::exe_name("btx-cli")),
            b"#!/bin/sh\nexec real\n",
        )
        .unwrap();
        // 64-bit little-endian Mach-O magic on disk reads big-endian as cf fa ed fe.
        let mut macho = vec![0xcfu8, 0xfa, 0xed, 0xfe];
        macho.extend_from_slice(&[0u8; 64]);
        std::fs::write(root.join("libexec").join("btxd.real"), &macho).unwrap();
        std::fs::write(
            root.join("libexec").join("metal").join("kernels.metallib"),
            b"shaders",
        )
        .unwrap();
    }

    #[test]
    fn provision_node_package_copies_tree_and_writes_conf() {
        let tmp = tempfile::tempdir().unwrap();
        let pkg = tmp.path().join("pkg");
        let install = tmp.path().join("install");
        let datadir = tmp.path().join("datadir");
        fake_node_pkg(&pkg);

        let res = provision_node_package(&pkg, &install, &datadir, NODE_FASTSTART_CONF).unwrap();

        assert_eq!(
            res.btxd,
            install.join("bin").join(crate::platform::exe_name("btxd"))
        );
        assert!(res.btxd.exists(), "wrapper must be copied");
        assert!(install.join("libexec").join("btxd.real").exists());
        assert!(
            install
                .join("libexec")
                .join("metal")
                .join("kernels.metallib")
                .exists(),
            "nested package dirs must be copied"
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&res.btxd).unwrap().permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "bin/btxd must be executable");
            let real = std::fs::metadata(install.join("libexec").join("btxd.real"))
                .unwrap()
                .permissions()
                .mode();
            assert_eq!(real & 0o111, 0o111, "libexec/btxd.real must be executable");
        }
        let conf = std::fs::read_to_string(&res.faststart_conf).unwrap();
        assert!(conf.contains("prune=0"));
        assert!(
            !conf.contains("miningminoutboundpeers"),
            "node preset must not carry mining keys"
        );
        assert!(res.mining_results_dir.is_none());
    }

    #[test]
    fn provision_node_package_errors_without_btxd_wrapper() {
        let tmp = tempfile::tempdir().unwrap();
        let pkg = tmp.path().join("pkg");
        std::fs::create_dir_all(pkg.join("bin")).unwrap(); // no btxd inside
        let err = provision_node_package(
            &pkg,
            &tmp.path().join("install"),
            &tmp.path().join("dd"),
            NODE_FASTSTART_CONF,
        );
        assert!(err.is_err(), "a package without bin/btxd must be rejected");
    }

    #[test]
    fn is_macho_detects_magic_and_rejects_scripts() {
        let tmp = tempfile::tempdir().unwrap();
        let script = tmp.path().join("wrapper");
        std::fs::write(&script, b"#!/bin/sh\necho hi\n").unwrap();
        assert!(!is_macho(&script));
        let macho64 = tmp.path().join("real");
        std::fs::write(&macho64, [0xcfu8, 0xfa, 0xed, 0xfe, 0, 0, 0, 0]).unwrap();
        assert!(is_macho(&macho64));
        let fat = tmp.path().join("fat");
        std::fs::write(&fat, [0xcau8, 0xfe, 0xba, 0xbe, 0, 0, 0, 2]).unwrap();
        assert!(is_macho(&fat));
        assert!(!is_macho(&tmp.path().join("missing")));
    }

    #[test]
    fn resolve_bundled_node_pkg_probes_bin_btxd() {
        let tmp = tempfile::tempdir().unwrap();
        // A dev root WITHOUT the package resolves to None.
        assert!(resolve_bundled_node_pkg(None, &[tmp.path()]).is_none());
        // With resources/node-pkg/bin/btxd present it resolves.
        let pkg = tmp.path().join("resources").join("node-pkg");
        std::fs::create_dir_all(pkg.join("bin")).unwrap();
        std::fs::write(
            pkg.join("bin").join(crate::platform::exe_name("btxd")),
            b"x",
        )
        .unwrap();
        assert_eq!(resolve_bundled_node_pkg(None, &[tmp.path()]), Some(pkg));
    }

    #[test]
    fn provision_node_package_accepts_flat_windows_layout() {
        // The Windows package we stage has no libexec/ wrapper split — just
        // bin/btxd.exe + bin/btx-cli.exe. Provision must succeed without a
        // libexec dir (the permission pass may simply find nothing there).
        let tmp = tempfile::tempdir().unwrap();
        let pkg = tmp.path().join("resources").join("node-pkg");
        let bin = pkg.join("bin");
        std::fs::create_dir_all(&bin).unwrap();
        std::fs::write(bin.join(crate::platform::exe_name("btxd")), b"stub").unwrap();
        std::fs::write(bin.join(crate::platform::exe_name("btx-cli")), b"stub").unwrap();
        let install = tmp.path().join("install");
        let datadir = tmp.path().join("data");
        std::fs::create_dir_all(&datadir).unwrap();
        let res = provision_node_package(&pkg, &install, &datadir, "conf=1\n").unwrap();
        assert!(res.btxd.exists(), "bin/btxd must be installed");
        assert!(res.btx_cli.exists(), "bin/btx-cli must be installed");
        assert_eq!(
            std::fs::read_to_string(res.faststart_conf).unwrap(),
            "conf=1\n"
        );
    }
}

#[cfg(test)]
mod keeper_profile_tests {
    use super::*;

    #[test]
    fn engine_gate_blocks_every_shipped_tag_and_admits_future_ones() {
        // Every tag the app has ever pinned predates the two required fixes.
        for old in ["v0.33.3-pr105b", "v0.33.2", "v0.33.1", "v0.33.0"] {
            assert!(!engine_supports_keeper_profile(old), "{old} must be gated");
            assert_eq!(
                conf_for_profile("keeper", old),
                NODE_FASTSTART_CONF,
                "keeper choice on {old} must provision the SAFE full conf"
            );
        }
        // A future re-pin tag passes (the release train adds it deliberately).
        assert!(engine_supports_keeper_profile("v0.33.3-pr105c"));
        assert_eq!(
            conf_for_profile("keeper", "v0.33.3-pr105c"),
            NODE_KEEPER_CONF
        );
    }

    #[test]
    fn full_profile_is_always_the_full_conf() {
        assert_eq!(
            conf_for_profile("full", "v0.33.3-pr105b"),
            NODE_FASTSTART_CONF
        );
        assert_eq!(
            conf_for_profile("full", "v0.33.3-pr105c"),
            NODE_FASTSTART_CONF
        );
        // Unknown strings degrade to the safe default too.
        assert_eq!(
            conf_for_profile("banana", "v0.33.3-pr105c"),
            NODE_FASTSTART_CONF
        );
    }

    #[test]
    fn keeper_conf_carries_the_profile_essentials() {
        assert!(NODE_KEEPER_CONF.contains("prune=10000"));
        assert!(NODE_KEEPER_CONF.contains("matmulattestationserve=1"));
        assert!(
            NODE_KEEPER_CONF.contains("parkdeepreorg=1"),
            "reorg posture kept"
        );
        assert!(
            NODE_KEEPER_CONF.contains("rpcbind=127.0.0.1"),
            "rpc stays local"
        );
    }
}
