//! The signer role: a node that validates blocks signs a confirmation for each
//! one, so the mirrors that cannot validate can follow it.
//!
//! ── WHY THIS EXISTS ─────────────────────────────────────────────────────────
//! btxscan.io's explorer runs on a trusted mirror. It cannot replay the MatMul
//! proof itself, so it accepts a block only once a key it pins has signed it.
//! Four keys are pinned there. One of them signs. It lives on an RTX 3060 in a
//! home. On 2026-09-16 at 15:23Z that machine was switched off and the mirror
//! froze at 221,448 while the network went on to 221,464 and past; a test
//! transaction sent through the frozen mirror was relayed and mined five
//! minutes later, so money moved and the explorer and both wallets could not
//! see it. Seventeen archive nodes helped nothing: they serve signatures and
//! cannot make them. The engine prints the diagnosis on every start:
//! "single-key trusted mirror ... configure a second independent signer".
//!
//! 0.6.23 solved the archive half (every GPU-less PC serves history as a
//! keyless mirror). The signer half had no path through the app at all: the
//! one signer was configured by hand, in a conf file, once.
//!
//! ── WHAT THIS DOES ──────────────────────────────────────────────────────────
//! On a node that validates in consensus mode, the app keeps ONE signing key in
//! the datadir, `attestation-signer.key`, and hands its path to the engine as
//! `matmulattestationsignerkeyfile`. The engine adds the corresponding public
//! key to its signer set and signs an attestation for every block it validates
//! (`getmatmultrustedstatus.local_signer = true`). The key is generated here,
//! once, the first time signing is on: measured against the shipped 0.34.6
//! engine on 2026-09-16, a MISSING key file is fatal at init ("Error: Cannot
//! read MatMul attestation signing key file"), so the engine does not make one
//! and the app has to.
//!
//! The file holds one WIF-encoded secp256k1 secret, exactly what the engine's
//! `-matmulattestationsignerkeyfile` help asks for: "a file containing exactly
//! one WIF signing key". The WIF version byte is BTX's own, 0x99, read from the
//! key this project's validator has signed with since 2026-09-01 (its WIF
//! begins with `P`; Bitcoin's 0x80 would begin with `K` or `L`), and verified
//! the way that counts: a key generated by this module, handed to the shipped
//! engine, reports `local_signer: true` and lists its public key in
//! `trusted_signer_pubkeys` (the test at the bottom of `node.rs` runs that
//! against a real btxd when one is present).
//!
//! ── WHAT THE OPERATOR IS BEING ASKED FOR ────────────────────────────────────
//! Trust, not bandwidth. At threshold one a pinned key is a full authority: a
//! mirror that pins this node's key takes its word for the proof of work and
//! never checks. So the public key is shown, with a copy button, and the copy
//! next to it says that out loud. The private key never leaves the datadir and
//! is never shown; the public key is public by construction, since every
//! attestation on the network carries it.
//!
//! A signature only helps a mirror that HEARS it. Attestations travel to
//! connected peers, and a node relays only the keys it pins, so a volunteer's
//! signature reaches the explorer's mirror only over a direct connection. A
//! signer therefore dials the mirrors this project feeds
//! ([`BTX_MIRRORS_FED_BY_SIGNERS`]) as manual peers, so the operator needs no
//! port forwarding and the mirror's admin needs exactly one line: the pin.
//!
//! ── "IS IT WORKING?" ────────────────────────────────────────────────────────
//! A key that signs nothing looks exactly like one that signs everything, from
//! the outside (2026-09-03: a key pinned in good faith on a mirror produced
//! nothing for eleven days). So the role card reads the node's own stored
//! attestations for the last [`SIGNED_WINDOW_BLOCKS`] blocks and says how many
//! carry this node's key. [`RecentSigners`] is that window, pure and tested;
//! [`refresh_recent_signers`] feeds it from RPC incrementally, so a running
//! node pays two calls per new block rather than two hundred per tick.

use crate::error::{AppError, AppResult};
use crate::rpc::Rpc;
use k256::elliptic_curve::sec1::ToEncodedPoint as _;
use serde::Serialize;
use std::collections::{BTreeMap, VecDeque};
use std::path::{Path, PathBuf};

/// The key file, inside the datadir. The same name this project's validator
/// has used since 2026-09-01, so that machine's existing key is adopted rather
/// than replaced when it updates.
pub const SIGNER_KEY_FILE: &str = "attestation-signer.key";

/// The engine option the file is handed to. A relative value resolves under
/// the network datadir, which for mainnet is the datadir itself.
pub const SIGNER_KEY_CONF_KEY: &str = "matmulattestationsignerkeyfile";

/// BTX's WIF version byte. Read from the validator's key (2026-09-16) and
/// proven against the engine, see the module doc.
pub const BTX_WIF_VERSION: u8 = 0x99;

/// How many recent blocks the "is it working" line looks at.
pub const SIGNED_WINDOW_BLOCKS: u64 = 100;

/// The trusted mirrors this project's signers feed. A signer dials them as
/// manual peers so its attestations arrive over a direct connection (see the
/// module doc for why relay does not carry them). Today: btxscan.io's mirror
/// on Azure, the node behind api.btxscan.io, which this project's validator
/// has kept a link to by hand since 2026-09-02.
///
/// One entry costs one of the engine's eight manual slots
/// (`node::MAX_MANUAL_PEERS`); a test in `node.rs` keeps the sum in budget.
pub const BTX_MIRRORS_FED_BY_SIGNERS: &[&str] = &["20.86.181.203:19338"];

/// The same mirrors as `whitelist=in,out,noban@<ip>` targets. A mirror
/// catching up asks its signer for attestations in bursts, and the engine
/// bans a peer whose `GETMMATTEST` traffic looks aggressive for 24 hours; the
/// validator's hand-kept conf has carried this line since day one for exactly
/// that reason.
pub const BTX_MIRROR_WHITELIST_IPS: &[&str] = &["20.86.181.203"];

/// The signing key on disk, described without its secret.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SignerKey {
    pub path: PathBuf,
    /// 66 lowercase hex characters: the compressed secp256k1 public key, the
    /// form the engine lists in `trusted_signer_pubkeys` and the form a mirror
    /// pins with `matmultrustedpubkey=`.
    pub pubkey_hex: String,
    /// True when this call generated the key; false when it read one that was
    /// already there.
    pub created: bool,
}

/// Where the key lives for a datadir.
pub fn signer_key_path(datadir: &Path) -> PathBuf {
    datadir.join(SIGNER_KEY_FILE)
}

/// A fresh WIF for BTX: version 0x99, a 32-byte secret the curve accepts, the
/// compressed-key flag, base58check.
///
/// The secret comes from the operating system's CSPRNG. A byte string outside
/// the curve order is rejected by `SecretKey::from_slice` and drawn again; the
/// probability is about 2^-128 per draw, so the loop is a formality that keeps
/// the function total.
pub fn generate_wif() -> String {
    use rand_core::RngCore as _;
    loop {
        let mut bytes = [0u8; 32];
        rand_core::OsRng.fill_bytes(&mut bytes);
        if k256::SecretKey::from_slice(&bytes).is_ok() {
            return wif_from_secret(&bytes);
        }
    }
}

fn wif_from_secret(secret: &[u8; 32]) -> String {
    let mut payload = Vec::with_capacity(34);
    payload.push(BTX_WIF_VERSION);
    payload.extend_from_slice(secret);
    payload.push(0x01); // compressed public key
    bs58::encode(payload).with_check().into_string()
}

/// The compressed public key a WIF signs as, as 66 lowercase hex characters.
///
/// Refuses anything that is not a BTX compressed WIF: wrong checksum, wrong
/// version byte, uncompressed form. The engine would refuse those too, at
/// init, with the node down; better to say so here while it is still up.
pub fn wif_to_pubkey_hex(wif: &str) -> AppResult<String> {
    let payload = bs58::decode(wif.trim())
        .with_check(None)
        .into_vec()
        .map_err(|e| AppError::Config(format!("signing key is not valid base58check: {e}")))?;
    if payload.len() != 34 {
        return Err(AppError::Config(format!(
            "signing key has {} payload bytes; a compressed WIF has 34",
            payload.len()
        )));
    }
    if payload[0] != BTX_WIF_VERSION {
        return Err(AppError::Config(format!(
            "signing key version byte is 0x{:02x}; BTX keys use 0x{:02x}",
            payload[0], BTX_WIF_VERSION
        )));
    }
    if payload[33] != 0x01 {
        return Err(AppError::Config(
            "signing key is not marked compressed; the engine pins compressed keys".to_string(),
        ));
    }
    let sk = k256::SecretKey::from_slice(&payload[1..33])
        .map_err(|_| AppError::Config("signing key secret is not on the curve".to_string()))?;
    let point = sk.public_key().to_encoded_point(true);
    Ok(hex_lower(point.as_bytes()))
}

fn hex_lower(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

/// Make sure the datadir holds a usable signing key, generating one only when
/// there is none.
///
/// An existing file is never overwritten, even when it does not parse: a key
/// file is the one thing in the datadir the app did not necessarily write (the
/// validator's was made by hand), and replacing it would silently retire a
/// key that mirrors pin. An unparseable file is an error the caller shows.
///
/// The file is created `0600` on Unix and written whole under a temporary
/// name before it takes its final name, so a crash mid-write leaves either no
/// key or a complete one. It holds one line: the WIF and a newline.
pub fn ensure_signer_key(datadir: &Path) -> AppResult<SignerKey> {
    let path = signer_key_path(datadir);
    if path.exists() {
        let wif = std::fs::read_to_string(&path).map_err(|e| {
            AppError::Config(format!("cannot read signing key {}: {e}", path.display()))
        })?;
        let pubkey_hex = wif_to_pubkey_hex(&wif)
            .map_err(|e| AppError::Config(format!("{}: {e}", path.display())))?;
        return Ok(SignerKey {
            path,
            pubkey_hex,
            created: false,
        });
    }
    std::fs::create_dir_all(datadir)
        .map_err(|e| AppError::Config(format!("cannot create {}: {e}", datadir.display())))?;
    let wif = generate_wif();
    let pubkey_hex = wif_to_pubkey_hex(&wif).expect("a key this module generated parses");
    write_private(&path, format!("{wif}\n").as_bytes())?;
    Ok(SignerKey {
        path,
        pubkey_hex,
        created: true,
    })
}

/// The public key of the key on disk, or `None` when there is no readable key.
/// For display: the status poll asks this and must not fail on a missing file.
pub fn read_signer_pubkey(datadir: &Path) -> Option<String> {
    let wif = std::fs::read_to_string(signer_key_path(datadir)).ok()?;
    wif_to_pubkey_hex(&wif).ok()
}

/// Write a secret: owner-only permissions from the first byte, and atomic.
fn write_private(path: &Path, bytes: &[u8]) -> AppResult<()> {
    use std::io::Write as _;
    let tmp = path.with_extension(format!("key.tmp-{}", std::process::id()));
    let mut opts = std::fs::OpenOptions::new();
    opts.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt as _;
        opts.mode(0o600);
    }
    let result = (|| -> std::io::Result<()> {
        let mut f = opts.open(&tmp)?;
        f.write_all(bytes)?;
        f.sync_all()?;
        std::fs::rename(&tmp, path)
    })();
    if let Err(e) = result {
        let _ = std::fs::remove_file(&tmp);
        return Err(AppError::Config(format!(
            "cannot write signing key {}: {e}",
            path.display()
        )));
    }
    Ok(())
}

/// Every signer public key an attestation carries.
///
/// The attestation wire format is the engine's and is not documented here;
/// what is stable, and what this reads, is the signature field: a
/// length-prefixed compressed public key (`21` then `02`/`03` and 32 bytes)
/// immediately followed by a length-prefixed DER signature (`44`..`48`, then
/// the `30` sequence tag). Measured on a version-2 attestation from this
/// project's validator at height 221,524 on 2026-09-16, and pinned by a test.
/// Any other 66-hex run in the attestation (hashes, the replay context) fails
/// the prefix-and-suffix shape and is not a key.
pub fn attestation_signer_pubkeys(attestation_hex: &str) -> Vec<String> {
    let h = attestation_hex.trim().to_ascii_lowercase();
    let b = h.as_bytes();
    let mut out = Vec::new();
    // Byte-aligned scan: the hex string is a byte string, so a field can only
    // start at an even offset.
    let mut i = 0;
    while i + 2 + 66 + 4 <= b.len() {
        if &b[i..i + 2] == b"21"
            && (&b[i + 2..i + 4] == b"02" || &b[i + 2..i + 4] == b"03")
            && b[i + 4..i + 68].iter().all(|c| c.is_ascii_hexdigit())
        {
            let sig_len = &b[i + 68..i + 70];
            let der_tag = &b[i + 70..i + 72];
            if matches!(sig_len, b"44" | b"45" | b"46" | b"47" | b"48") && der_tag == b"30" {
                let key = h[i + 2..i + 68].to_string();
                if !out.contains(&key) {
                    out.push(key);
                }
                i += 68;
                continue;
            }
        }
        i += 2;
    }
    out
}

/// A rolling window over the newest blocks: who signed each one.
///
/// Pure. Fed by [`refresh_recent_signers`] on a live node and by tests
/// directly. Holds at most [`SIGNED_WINDOW_BLOCKS`] heights; a height recorded
/// twice (a reorg replaced the block, or the newest block gained a signature
/// after it was first read) replaces the earlier entry.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RecentSigners {
    /// Oldest first. `(height, hash, signer pubkeys)`.
    entries: VecDeque<(u64, String, Vec<String>)>,
}

/// What the window says, for a person or for the census.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct RecentSignersSummary {
    /// Blocks looked at: the window's target size.
    pub window: u64,
    /// Blocks actually read so far (fewer than `window` right after a start).
    pub seen: u64,
    /// The newest height in the window, or 0 when empty.
    pub tip: u64,
    /// Blocks in the window that carry at least one signature.
    pub blocks_with_signature: u64,
    /// Distinct public keys seen across the window.
    pub distinct_keys: u64,
    /// Blocks signed, per public key.
    pub keys: BTreeMap<String, u64>,
}

impl RecentSigners {
    pub fn new() -> Self {
        Self::default()
    }

    /// Record the signers of one block. Heights arrive in any order; the
    /// window keeps the newest `SIGNED_WINDOW_BLOCKS` of them.
    pub fn record(&mut self, height: u64, hash: &str, attestation_hexes: &[String]) {
        let mut keys: Vec<String> = Vec::new();
        for a in attestation_hexes {
            for k in attestation_signer_pubkeys(a) {
                if !keys.contains(&k) {
                    keys.push(k);
                }
            }
        }
        self.entries.retain(|(h, _, _)| *h != height);
        let pos = self.entries.partition_point(|(h, _, _)| *h < height);
        self.entries.insert(pos, (height, hash.to_string(), keys));
        while self.entries.len() as u64 > SIGNED_WINDOW_BLOCKS {
            self.entries.pop_front();
        }
    }

    /// The newest height recorded, if any.
    pub fn highest(&self) -> Option<u64> {
        self.entries.back().map(|(h, _, _)| *h)
    }

    /// The hash recorded at a height, if that height is in the window.
    pub fn hash_at(&self, height: u64) -> Option<&str> {
        self.entries
            .iter()
            .find(|(h, _, _)| *h == height)
            .map(|(_, hash, _)| hash.as_str())
    }

    /// Which heights to read next so the window covers the `SIGNED_WINDOW_BLOCKS`
    /// blocks up to `tip`, oldest first, at most `budget` of them.
    ///
    /// Entries below the window's floor are dropped first, so a node that was
    /// stopped for a day does not keep yesterday's heights. The newest recorded
    /// height is included again: the block at the tip is often read before its
    /// signature is stored, and a reorg can replace it, so it is always worth
    /// one more look (its cost is two RPCs).
    pub fn heights_to_read(&mut self, tip: u64, budget: usize) -> Vec<u64> {
        let floor = tip.saturating_sub(SIGNED_WINDOW_BLOCKS - 1);
        self.entries.retain(|(h, _, _)| *h >= floor && *h <= tip);
        let mut out = Vec::new();
        let mut h = floor;
        while h <= tip && out.len() < budget {
            let known = self.entries.iter().any(|(k, _, _)| *k == h);
            if !known || h == tip || Some(h) == self.highest() {
                out.push(h);
            }
            h += 1;
        }
        out
    }

    pub fn summary(&self) -> RecentSignersSummary {
        let mut keys: BTreeMap<String, u64> = BTreeMap::new();
        let mut with_sig = 0u64;
        for (_, _, ks) in &self.entries {
            if !ks.is_empty() {
                with_sig += 1;
            }
            for k in ks {
                *keys.entry(k.clone()).or_insert(0) += 1;
            }
        }
        RecentSignersSummary {
            window: SIGNED_WINDOW_BLOCKS,
            seen: self.entries.len() as u64,
            tip: self.highest().unwrap_or(0),
            blocks_with_signature: with_sig,
            distinct_keys: keys.len() as u64,
            keys,
        }
    }

    /// How many blocks in the window carry `pubkey_hex`, with how many were
    /// looked at.
    pub fn signed_by(&self, pubkey_hex: &str) -> SignedRecent {
        let want = pubkey_hex.to_ascii_lowercase();
        SignedRecent {
            signed: self
                .entries
                .iter()
                .filter(|(_, _, ks)| ks.contains(&want))
                .count() as u64,
            seen: self.entries.len() as u64,
            window: SIGNED_WINDOW_BLOCKS,
        }
    }
}

/// "Your key was on N of the last M blocks", for the role card.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct SignedRecent {
    pub signed: u64,
    /// Blocks actually examined; `signed` is out of this, not out of `window`.
    pub seen: u64,
    pub window: u64,
}

/// Bring the window up to `tip` from the node, reading at most `budget`
/// heights this call (two RPCs each: `getblockhash`, `getmatmulattestations`).
///
/// A failed read leaves that height unrecorded and stops the pass; the next
/// call picks it up. Never an error: a window that is short of a few blocks is
/// still a true statement about the blocks it holds.
pub async fn refresh_recent_signers(
    rpc: &dyn Rpc,
    window: &mut RecentSigners,
    tip: u64,
    budget: usize,
) {
    for h in window.heights_to_read(tip, budget) {
        let Ok(v) = rpc.call("getblockhash", serde_json::json!([h])).await else {
            return;
        };
        let Some(hash) = v.as_str().map(str::to_string) else {
            return;
        };
        let Ok(a) = rpc
            .call("getmatmulattestations", serde_json::json!([hash]))
            .await
        else {
            return;
        };
        let atts: Vec<String> = a
            .as_array()
            .map(|xs| {
                xs.iter()
                    .filter_map(|x| x.as_str().map(str::to_string))
                    .collect()
            })
            .unwrap_or_default();
        window.record(h, &hash, &atts);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A version-2 attestation from this project's validator, block 221,524
    /// (hash 2c8d3ecb…979a), read with `getmatmulattestations` on 2026-09-16.
    /// The signer is the validator's key, 02d5ef…4675.
    const REAL_ATTESTATION: &str = "020146faf0ab1a2bba35d46cc0395810c4099365cce27dcaa9256e2d9da398a9759a978c191a323620660e05c3f26e4b678040f642ed71d5d79b2e9343cb3e8d2c5461030004018871af09bde2d5cded09bcf4fd41ccc979680bdc6125312a754981142e5cad322102d5efca78b53c89e7e1672feda8a9b70937bba40b001413495e86e05f196c467546304402205aed6d07d5673463ec7f146de5fa4095ec01ec3c18517835350d8d3317a8ffd7022036cfee81d4408cd634581c48976de2c61ed5bf31a5f45d1763da4833a8d72514";
    const VALIDATOR_KEY: &str =
        "02d5efca78b53c89e7e1672feda8a9b70937bba40b001413495e86e05f196c4675";

    #[test]
    fn a_generated_key_round_trips_and_has_the_btx_shape() {
        let wif = generate_wif();
        // BTX's 0x99 version byte puts every compressed WIF in the `P` range,
        // where Bitcoin's 0x80 gives `K` or `L`. The validator's key starts
        // with `P` and this is the same alphabet arithmetic.
        assert!(wif.starts_with('P'), "{wif}");
        assert_eq!(wif.len(), 52, "{wif}");
        let pk = wif_to_pubkey_hex(&wif).unwrap();
        assert_eq!(pk.len(), 66);
        assert!(pk.starts_with("02") || pk.starts_with("03"), "{pk}");
        assert!(pk
            .bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase()));
        // Two draws are two keys.
        assert_ne!(generate_wif(), wif);
    }

    #[test]
    fn a_known_secret_gives_a_known_public_key() {
        // secret = 1: the generator point, compressed. A vector every secp256k1
        // implementation agrees on, so a wrong curve or a wrong compression
        // flag fails here rather than at the engine.
        let mut secret = [0u8; 32];
        secret[31] = 1;
        let wif = wif_from_secret(&secret);
        assert_eq!(
            wif_to_pubkey_hex(&wif).unwrap(),
            "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
        );
    }

    #[test]
    fn foreign_and_broken_keys_are_refused_with_a_reason() {
        // Bitcoin mainnet compressed WIF for secret 1 (version 0x80).
        let bitcoin = "KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn";
        let e = wif_to_pubkey_hex(bitcoin).unwrap_err().to_string();
        assert!(e.contains("0x80") && e.contains("0x99"), "{e}");
        let e = wif_to_pubkey_hex("not a key").unwrap_err().to_string();
        assert!(e.contains("base58check"), "{e}");
        let mut secret = [0u8; 32];
        secret[31] = 1;
        let mut payload = vec![BTX_WIF_VERSION];
        payload.extend_from_slice(&secret); // no compression flag
        let uncompressed = bs58::encode(payload).with_check().into_string();
        let e = wif_to_pubkey_hex(&uncompressed).unwrap_err().to_string();
        assert!(e.contains("34"), "{e}");
    }

    #[test]
    fn ensure_creates_once_then_reads_and_never_overwrites() {
        let dir = tempfile::tempdir().unwrap();
        let first = ensure_signer_key(dir.path()).unwrap();
        assert!(first.created);
        assert_eq!(first.path, dir.path().join(SIGNER_KEY_FILE));
        let on_disk = std::fs::read_to_string(&first.path).unwrap();
        assert!(on_disk.ends_with('\n') && on_disk.trim().len() == 52);
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&first.path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o600, "a secret is owner-only from the first byte");
        }
        let second = ensure_signer_key(dir.path()).unwrap();
        assert!(!second.created);
        assert_eq!(
            second.pubkey_hex, first.pubkey_hex,
            "the same key is read back"
        );
        assert_eq!(
            read_signer_pubkey(dir.path()).as_deref(),
            Some(first.pubkey_hex.as_str())
        );
        // No temp file left behind.
        assert_eq!(std::fs::read_dir(dir.path()).unwrap().count(), 1);

        // A file that does not parse is reported, not replaced.
        std::fs::write(&first.path, "garbage\n").unwrap();
        let e = ensure_signer_key(dir.path()).unwrap_err().to_string();
        assert!(e.contains(SIGNER_KEY_FILE), "{e}");
        assert_eq!(std::fs::read_to_string(&first.path).unwrap(), "garbage\n");
        assert_eq!(read_signer_pubkey(dir.path()), None);
    }

    #[test]
    fn the_validators_real_attestation_names_its_key_and_nothing_else() {
        assert_eq!(
            attestation_signer_pubkeys(REAL_ATTESTATION),
            vec![VALIDATOR_KEY.to_string()]
        );
        // Case-insensitive, and a hash-shaped run is not a key.
        assert_eq!(
            attestation_signer_pubkeys(&REAL_ATTESTATION.to_ascii_uppercase()),
            vec![VALIDATOR_KEY.to_string()]
        );
        assert!(attestation_signer_pubkeys("02deadbeef").is_empty());
        assert!(attestation_signer_pubkeys("").is_empty());
    }

    fn att(key: &str) -> String {
        // The signature field shape only: prefix, key, DER length, DER tag.
        format!("00ff21{key}463044deadbeef")
    }

    #[test]
    fn the_window_counts_signers_and_keeps_the_newest_hundred() {
        let a = "02".to_string() + &"a".repeat(64);
        let b = "03".to_string() + &"b".repeat(64);
        let mut w = RecentSigners::new();
        for h in 1..=150u64 {
            let atts = if h % 2 == 0 {
                vec![att(&a)]
            } else {
                vec![att(&a), att(&b)]
            };
            w.record(h, &format!("h{h}"), &atts);
        }
        let s = w.summary();
        assert_eq!(s.seen, 100);
        assert_eq!(s.tip, 150);
        assert_eq!(s.blocks_with_signature, 100);
        assert_eq!(s.distinct_keys, 2);
        assert_eq!(s.keys[&a], 100);
        assert_eq!(s.keys[&b], 50);
        assert_eq!(
            w.signed_by(&b),
            SignedRecent {
                signed: 50,
                seen: 100,
                window: 100
            }
        );
        assert_eq!(w.signed_by(&a.to_ascii_uppercase()).signed, 100);
        assert_eq!(w.hash_at(150), Some("h150"));
        assert_eq!(w.hash_at(50), None, "below the window");

        // A block with no attestation counts as seen and unsigned.
        w.record(151, "h151", &[]);
        assert_eq!(w.summary().blocks_with_signature, 99);
        // Re-recording a height replaces it (a reorg, or a late signature).
        w.record(151, "h151b", &[att(&b)]);
        assert_eq!(w.summary().blocks_with_signature, 100);
        assert_eq!(w.summary().seen, 100);
        assert_eq!(w.hash_at(151), Some("h151b"));
    }

    #[test]
    fn heights_to_read_fills_the_window_then_costs_two_calls_per_block() {
        let mut w = RecentSigners::new();
        // Empty window at tip 500: the first pass wants the oldest 25 of the
        // window (401..=425), oldest first, so a restart recovers in a few ticks.
        assert_eq!(w.heights_to_read(500, 25), (401..=425).collect::<Vec<_>>());
        for h in 401..=500 {
            w.record(h, &format!("h{h}"), &[]);
        }
        // Full and at the tip: only the tip is re-read.
        assert_eq!(w.heights_to_read(500, 25), vec![500]);
        // One new block: the old tip (its signature may have landed since) and
        // the new one.
        assert_eq!(w.heights_to_read(501, 25), vec![500, 501]);
        // The floor moved, so height 401 is gone.
        assert_eq!(w.hash_at(401), None);
        assert_eq!(w.summary().seen, 99);
        // A node that was off for a day: the window is discarded and refilled.
        let far = w.heights_to_read(10_000, 25);
        assert_eq!(far, (9901..=9925).collect::<Vec<_>>());
        assert_eq!(w.summary().seen, 0);
    }

    /// The proof that matters: the shipped engine accepts a key this module
    /// generated and signs as it. Runs only when `EASYNODE_TEST_BTXD` names a
    /// btxd (the app's own install dir has one), offline, in a scratch
    /// datadir, with its own ports:
    ///
    /// ```text
    /// EASYNODE_TEST_BTXD=~/.local/btx/v0.34.5/linux-x86_64/bin/btxd \
    ///   cargo test --lib signer::tests::the_shipped_engine_signs_with_a_generated_key -- --ignored
    /// ```
    ///
    /// Passed on 2026-09-16 against btxd 0.34.6 (`v0.34.6-3013c2c2`).
    #[tokio::test]
    #[ignore]
    async fn the_shipped_engine_signs_with_a_generated_key() {
        let Some(btxd) = std::env::var_os("EASYNODE_TEST_BTXD") else {
            eprintln!("EASYNODE_TEST_BTXD unset; nothing to test against");
            return;
        };
        let dir = tempfile::tempdir().unwrap();
        let key = ensure_signer_key(dir.path()).unwrap();
        assert!(key.created);
        let mut child = std::process::Command::new(&btxd)
            .arg(format!("-datadir={}", dir.path().display()))
            .args([
                "-listen=0",
                "-connect=0",
                "-dnsseed=0",
                "-upnp=0",
                "-natpmp=0",
                "-rpcport=29434",
                "-port=29435",
                "-rpcbind=127.0.0.1",
                "-rpcallowip=127.0.0.1",
                "-server=1",
                "-prune=550",
                "-matmulvalidation=consensus",
                "-allowunverifiablematmulconsensus=1",
                "-printtoconsole=0",
                "-daemon=0",
            ])
            .arg(format!("-{SIGNER_KEY_CONF_KEY}={SIGNER_KEY_FILE}"))
            .spawn()
            .expect("btxd spawns");
        let cookie = dir.path().join(".cookie");
        let mut status = None;
        for _ in 0..60 {
            tokio::time::sleep(std::time::Duration::from_millis(500)).await;
            if let Some(code) = child.try_wait().unwrap() {
                panic!("btxd exited early with {code}: the engine refused the key");
            }
            if !cookie.exists() {
                continue;
            }
            let Ok(rpc) =
                crate::rpc::RpcClient::from_cookie("http://127.0.0.1:29434".to_string(), &cookie)
            else {
                continue;
            };
            if let Ok(v) = rpc
                .call("getmatmultrustedstatus", serde_json::json!([]))
                .await
            {
                status = Some((rpc, v));
                break;
            }
        }
        let (rpc, v) = status.expect("btxd answered getmatmultrustedstatus within 30 s");
        let _ = rpc.call("stop", serde_json::json!([])).await;
        let _ = child.wait();
        assert_eq!(v["local_signer"], true, "{v}");
        let listed = v["trusted_signer_pubkeys"]
            .as_array()
            .map(|a| {
                a.iter()
                    .any(|k| k.as_str() == Some(key.pubkey_hex.as_str()))
            })
            .unwrap_or(false);
        assert!(listed, "our key {} is not in {v}", key.pubkey_hex);
    }

    #[test]
    fn summary_of_an_empty_window_claims_nothing() {
        let s = RecentSigners::new().summary();
        assert_eq!(s.seen, 0);
        assert_eq!(s.tip, 0);
        assert_eq!(s.distinct_keys, 0);
        assert!(s.keys.is_empty());
    }
}
